Flutter Firebase & DDD Course [14] - Data Transfer Objects
・ Prepare the Data Transfer Object (DTOs) inside the Infrastructure layer

* One using "FieldValue serverTimeStamp", is a new concept and it's pretty cool :) (May need to review later!)

* Note that the project won't compile now with the below error. I'm hoping ResoCoder will show us how to make this error go away.

PS C:\data\codespace\flutter\flutter-ddd-firebase-course> flutter run

Launching lib\main.dart on SM A715F in debug mode...
D8: Cannot fit requested classes in a single dex file (# methods: 88457 > 65536)
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
The number of method references in a .dex file cannot exceed 64K.
...
BUILD FAILED in 20s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        22.2s
[!] The shrinker may have failed to optimize the Java bytecode.
    To disable the shrinker, pass the `--no-shrink` flag to this command.
    To learn more, see: https://developer.android.com/studio/build/shrink-code